name: Build and Deploy

on:
  push:
    branches:
      - main
      - master

jobs:
  build-and-push:
    runs-on: build
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and Push Docker image
        run: |
          docker system prune -af
          docker build -t ghcr.io/bjornarron/flask-example .
          docker login ghcr.io --username bjornarron --password ${{ secrets.PAT_DEVOPS }}
          docker push ghcr.io/bjornarron/flask-example
  deploy:
    runs-on: deployment
    needs: build-and-push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        
      - name: Deploy docker image for flask on VM
        run: |
            docker login ghcr.io --username bjornarron --password ${{ secrets.PAT_DEVOPS }}
            docker stop $(docker ps -aq) && docker rm $(docker ps -aq)
            docker compose up -d


